version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - amqp-net

  amqp-proxy-zig:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amqp-proxy-zig
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - AMQP_HOST=rabbitmq
    networks:
      - amqp-net

  amqp-producer1:
    build:
      context: ./rabbit-producer
      dockerfile: Dockerfile
    container_name: amqp-producer1
    depends_on:
      rabbitmq:
        condition: service_healthy
      amqp-proxy-zig:
        condition: service_started
    environment:
      - RABBITMQ_HOST=amqp-proxy-zig
    networks:
      - amqp-net

  amqp-producer2:
    build:
      context: ./rabbit-producer
      dockerfile: Dockerfile
    container_name: amqp-producer2
    depends_on:
      rabbitmq:
        condition: service_healthy
      amqp-proxy-zig:
        condition: service_started
    environment:
      - RABBITMQ_HOST=amqp-proxy-zig
    networks:
      - amqp-net

networks:
  amqp-net:
